name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"   # executa a cada 6 horas
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gera Snake Animation SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Robert-Amorim
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Publica no branch output
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
